export enum Routes {
  HOMEPAGE = '/',
  ABOUT = 'about',
  TEAM = 'team',
  TEAM_SLUG = 'team-slug',
  CONTACTS = 'contacts',
  BLOG = 'blog',
  BLOG_SLUG = 'blog-slug',
  BLOG_CATEGORIES = 'blog-categories',
  BLOG_CATEGORIES_SLUG = 'blog-categories-slug',
  BLOG_AUTHORS = 'blog-authors',
  BLOG_AUTHORS_SLUG = 'blog-authors-slug',
  SERVICES = 'services',
  SERVICES_SLUG = 'services-slug',
  PARTNERSHIPS = 'partnerships',
  RECRUITMENT = 'recruitment',
  FAQ = 'faq',
  SEARCH = '/',
  PRIVACY_POLICY = 'privacy-policy',
  NOT_FOUND = '404',
}
