export enum Routes {
  HOMEPAGE = '/',
  ABOUT = 'about',
  TEAM = 'team',
  CONTACTS = 'contacts',
  BLOG = 'blog',
  BLOG_SLUG = 'blog-slug',
  BLOG_CATEGORIES = 'blog-categories',
  BLOG_CATEGORIES_SLUG = 'blog-categories-slug',
  SERVICES = 'services',
  PARTNERSHIPS = 'partnerships',
  RECRUITMENT = 'recruitment',
  FAQ = 'faq',
  SEARCH = 'search',
  NOT_FOUND = '404',
}
